### ISSUE TITLE
IESKF收敛判断

### ISSUE THREAD

**Issue by Awaker1** [mengkai98/ieskf_slam#2]
https://github.com/mengkai98/ieskf_slam/blob/96e6695ea001f31f19867a9ace3be2764f227dac/src/ieskf_slam/modules/ieskf/ieskf.cpp#L99-L105
请问在这里对迭代收敛判断中，以`idx`为索引进行18次循环，但是判断的都是同一个值，是否存在某些问题？
以我粗浅的理解，这里是否是要对所有状态量的迭代增量进行判断呢？

**Comment by mengkai98** [comment]
是有这样一个问题，我已经在1-7中修复了这个错误(*￣︶￣)
