### ISSUE TITLE
关于地图管理模块的bug

### ISSUE THREAD

**Issue by yuhang9803** [mengkai98/ieskf_slam#3]
hello，我最近在按照的你的思路写算法的时候发现您的地图管理模块有一个bug，就是当xyz都要超出边界的时候才会right--，实际上我遇到了x超出边界，yz不超出的情况，这个时候就会一直在外面的while里循环，因为既进不了right--的逻辑也进不了left++的逻辑

**Comment by mengkai98** [comment]
是的，第一个while循环判断点是否在外面应该用“或”逻辑，谢谢你的发现
